"""
plot_comparison.py - Training Curve Comparison Plotter
======================================================
Generates a 2-panel comparison plot showing how different agents (random,
baseline DQN, reward-shaped DQN) performed on the same MiniGrid environment.

The plots use Epsilon (exploration rate) as the X-axis instead of timesteps.
This lets us directly see how performance changes as the agent shifts from
exploration (high epsilon) to exploitation (low epsilon).

Panel 1: Episodic Return vs Epsilon
  - Shows the smoothed average reward per episode at each epsilon value.
  - Higher is better. A flat line (like the random agent) means no learning.

Panel 2: Goal Reached Rate vs Epsilon
  - Shows the smoothed probability of reaching the goal at each epsilon value.
  - Range is 0.0 (never reaches goal) to 1.0 (always reaches goal).

The script automatically finds the LATEST run for each experiment type
(random_agent, dqn_baseline, dqn_reward_shaping) in the results directory,
so you never need to manually specify run folder names.

Usage:
  python plot_comparison.py --env-id MiniGrid-Empty-8x8-v0
  python plot_comparison.py --env-id MiniGrid-DoorKey-8x8-v0 --rolling-window 30

Output:
  plots/<env_id>_comparison.png
"""

# ============================================================================
# STANDARD LIBRARY IMPORTS
# ============================================================================

# argparse: Parses command-line arguments (--env-id, --results-dir, etc.)
import argparse

# csv: Reads the episodes.csv files generated by the training scripts.
#   csv.DictReader reads each row as a dictionary with column names as keys.
import csv

# json: Reads config.json files to extract experiment names and seeds.
import json

# Path: Object-oriented filesystem paths for directory traversal and file checks.
from pathlib import Path

# ============================================================================
# THIRD-PARTY IMPORTS
# ============================================================================

# matplotlib.pyplot (plt): The standard Python library for creating static plots.
#   plt.subplots() creates a figure with multiple subplots.
#   ax.plot() draws a line on a subplot.
#   fig.savefig() saves the figure to an image file.
import matplotlib.pyplot as plt

# numpy (np): Used for computing the rolling mean (moving average) to smooth the plots.
import numpy as np


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def rolling(values, window):
    """
    Computes a rolling (moving) average over a list of values.

    Why we need this:
      Raw episode returns are very noisy (one episode might return 0.95 and
      the next 0.0). Plotting raw values creates an unreadable spiky chart.
      The rolling average smooths these spikes into a readable trend line.

    How it works:
      For each position i, it averages all values from max(0, i - window + 1) to i.
      At the beginning of the list (where fewer than 'window' values are available),
      it uses all available values (partial window).

    Parameters
    ----------
    values : list[float]
        The raw metric values to smooth (e.g., episodic returns).
    window : int
        The number of recent values to average over.
        Larger window = smoother but less responsive to recent changes.

    Returns
    -------
    list[float]
        The smoothed values, same length as the input.
    """
    if len(values) == 0:
        return values
    out = []
    for i in range(len(values)):
        start = max(0, i - window + 1)
        out.append(float(np.mean(values[start : i + 1])))
    return out


def load_runs(results_dir, env_id):
    """
    Scans the results directory for all experiment runs matching a specific environment,
    and returns only the LATEST run for each experiment type.

    How it works:
      1. Uses Path.glob() to find all directories matching "{env_id}__*" pattern.
         For example, for env_id="MiniGrid-Empty-8x8-v0", it finds:
           - MiniGrid-Empty-8x8-v0__dqn_baseline__1__1718300000
           - MiniGrid-Empty-8x8-v0__dqn_baseline__1__1718310000  (newer)
           - MiniGrid-Empty-8x8-v0__random_agent__1__1718300500

      2. Directories are sorted alphabetically. Since the timestamp is the last
         component, chronologically newer runs come later in the sorted order.

      3. For each run, it reads config.json (to get exp_name like "dqn_baseline")
         and episodes.csv (to get the actual training data).

      4. It stores runs in a dictionary keyed by exp_name. When multiple runs
         have the same exp_name, the later one (newer timestamp) overwrites
         the earlier one, ensuring we only keep the latest.

    Parameters
    ----------
    results_dir : str
        Path to the directory containing run folders (default: "results").
    env_id : str
        The gymnasium environment ID to filter runs for.

    Returns
    -------
    list[tuple]
        A list of (run_dir_name, config_dict, rows_list) tuples, one per experiment type.
        Each row in rows_list is a dict with keys: global_step, episodic_return,
        goal_reached, epsilon.
    """
    runs_by_exp = {}

    # sorted() ensures directories are processed in chronological order (by timestamp)
    for run_dir in sorted(Path(results_dir).glob(f"{env_id}__*")):
        config_path = run_dir / "config.json"
        episode_path = run_dir / "episodes.csv"

        # Skip incomplete runs (missing config or episode data)
        if not config_path.exists() or not episode_path.exists():
            continue

        # Read the experiment configuration
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)

        # Read all episode-level metrics from the CSV file
        rows = []
        with open(episode_path, "r", encoding="utf-8") as f:
            # csv.DictReader automatically uses the first row as column headers
            for row in csv.DictReader(f):
                rows.append(
                    {
                        "global_step": int(row["global_step"]),
                        "episodic_return": float(row["episodic_return"]),
                        "goal_reached": float(row["goal_reached"]),
                        "epsilon": float(row["epsilon"]),
                    }
                )

        if rows:
            # Key by exp_name (e.g., "dqn_baseline"). If a newer run exists for
            # the same exp_name, it overwrites the older one (because we sorted).
            runs_by_exp[config["exp_name"]] = (run_dir.name, config, rows)

    return list(runs_by_exp.values())


# ============================================================================
# MAIN PLOTTING FUNCTION
# ============================================================================

def main():
    """
    Entry point: parses arguments, loads runs, and generates the comparison plot.
    """
    parser = argparse.ArgumentParser()

    # --env-id (required): Which environment's results to plot.
    parser.add_argument("--env-id", type=str, required=True)

    # --results-dir: Where to look for run folders (default: "results").
    parser.add_argument("--results-dir", type=str, default="results")

    # --plots-dir: Where to save the output plot image (default: "plots").
    parser.add_argument("--plots-dir", type=str, default="plots")

    # --rolling-window: How many episodes to average over for smoothing.
    #   A window of 20 means each plotted point is the average of the last 20 episodes.
    #   Increase this for noisier environments (e.g., DoorKey) to see clearer trends.
    parser.add_argument("--rolling-window", type=int, default=20)

    args = parser.parse_args()

    # Load all latest runs for this environment
    runs = load_runs(args.results_dir, args.env_id)
    if not runs:
        raise SystemExit(f"No runs found for {args.env_id} in {args.results_dir}")

    # Create the output directory if it doesn't exist
    Path(args.plots_dir).mkdir(parents=True, exist_ok=True)

    # --- Create the Figure ---
    # plt.subplots(2, 1) creates 2 vertically stacked subplots sharing the same X-axis.
    # figsize=(10, 8) sets the figure size in inches (width, height).
    # sharex=True links the X-axis zoom/pan between the two panels.
    fig, axes = plt.subplots(2, 1, figsize=(10, 8), sharex=True)

    # --- Plot Each Agent's Data ---
    for _, config, rows in runs:
        # Create a descriptive label for the legend (e.g., "dqn_baseline seed=1")
        label = f"{config['exp_name']} seed={config['seed']}"

        # Apply rolling average smoothing to the metrics
        returns = rolling([r["episodic_return"] for r in rows], args.rolling_window)
        goals = rolling([r["goal_reached"] for r in rows], args.rolling_window)

        # Extract the epsilon values (X-axis)
        epsilons = [r["epsilon"] for r in rows]

        # Plot Return vs Epsilon (top panel)
        axes[0].plot(epsilons, returns, label=label)

        # Plot Goal Rate vs Epsilon (bottom panel)
        axes[1].plot(epsilons, goals, label=label)

    # --- Configure Top Panel: Episodic Return ---
    axes[0].set_title(f"{args.env_id} episodic return vs epsilon")
    axes[0].set_ylabel("Return")
    axes[0].grid(alpha=0.3)  # Light grid lines for readability

    # --- Configure Bottom Panel: Goal Reached Rate ---
    axes[1].set_title(f"{args.env_id} goal reached rate vs epsilon")
    axes[1].set_ylabel("Goal rate")
    axes[1].set_xlabel("Epsilon")
    axes[1].set_ylim(-0.05, 1.05)  # Goal rate ranges from 0.0 to 1.0

    # Invert the X-axis so that time flows left-to-right:
    #   Left side = high epsilon (start of training, lots of exploration)
    #   Right side = low epsilon (end of training, mostly exploitation)
    # Without this, the plot would flow right-to-left which is counterintuitive.
    axes[1].invert_xaxis()
    axes[1].grid(alpha=0.3)

    # Show legends on both panels so you can identify which line is which agent
    axes[0].legend()
    axes[1].legend()

    # tight_layout() automatically adjusts spacing between subplots to prevent overlap
    fig.tight_layout()

    # --- Save the Plot ---
    out = Path(args.plots_dir) / f"{args.env_id}_comparison.png"
    fig.savefig(out, dpi=160)  # dpi=160 gives a high-resolution image
    print(f"Saved {out}")


if __name__ == "__main__":
    main()
