"""
plot_comparison.py - Training Curve Comparison Plotter
======================================================
Generates a 2-panel comparison plot showing how different agents (random,
baseline DQN, reward-shaped DQN) performed on the same MiniGrid environment.

The plots use Epsilon (exploration rate) as the X-axis instead of timesteps.
This lets us directly see how performance changes as the agent shifts from
exploration (high epsilon) to exploitation (low epsilon).

Panel 1: Episodic Return vs Epsilon
  - Shows the smoothed average reward per episode at each epsilon value.
  - Higher is better. A flat line (like the random agent) means no learning.

Panel 2: Goal Reached Rate vs Epsilon
  - Shows the smoothed probability of reaching the goal at each epsilon value.
  - Range is 0.0 (never reaches goal) to 1.0 (always reaches goal).

The script automatically finds the LATEST run for each experiment type
(random_agent, dqn_baseline, dqn_reward_shaping) in the results directory,
so you never need to manually specify run folder names.

Usage:
  python plot_comparison.py --env-id MiniGrid-Empty-8x8-v0
  python plot_comparison.py --env-id MiniGrid-DoorKey-8x8-v0 --rolling-window 30

Output:
  plots/<env_id>_comparison.png
"""

# ============================================================================
# STANDARD LIBRARY IMPORTS
# ============================================================================

# argparse: Parses command-line arguments (--env-id, --results-dir, etc.)
import argparse

# csv: Reads the episodes.csv files generated by the training scripts.
#   csv.DictReader reads each row as a dictionary with column names as keys.
import csv

# json: Reads config.json files to extract experiment names and seeds.
import json

# Path: Object-oriented filesystem paths for directory traversal and file checks.
from pathlib import Path

# ============================================================================
# THIRD-PARTY IMPORTS
# ============================================================================

# matplotlib.pyplot (plt): The standard Python library for creating static plots.
#   plt.subplots() creates a figure with multiple subplots.
#   ax.plot() draws a line on a subplot.
#   fig.savefig() saves the figure to an image file.
import matplotlib.pyplot as plt

# numpy (np): Used for computing the rolling mean (moving average) to smooth the plots.
import numpy as np


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def rolling(values, window):
    """
    Computes a rolling (moving) average over a list of values.

    Why we need this:
      Raw episode returns are very noisy (one episode might return 0.95 and
      the next 0.0). Plotting raw values creates an unreadable spiky chart.
      The rolling average smooths these spikes into a readable trend line.

    How it works:
      For each position i, it averages all values from max(0, i - window + 1) to i.
      At the beginning of the list (where fewer than 'window' values are available),
      it uses all available values (partial window).

    Parameters
    ----------
    values : list[float]
        The raw metric values to smooth (e.g., episodic returns).
    window : int
        The number of recent values to average over.
        Larger window = smoother but less responsive to recent changes.

    Returns
    -------
    list[float]
        The smoothed values, same length as the input.
    """
    if len(values) == 0:
        return values
    out = []
    for i in range(len(values)):
        start = max(0, i - window + 1)
        out.append(float(np.mean(values[start : i + 1])))
    return out


def load_runs(results_dir, env_id):
    """
    Scans the results directory for all experiment runs matching a specific environment,
    and returns only the LATEST run for each experiment type.

    How it works:
      1. Uses Path.glob() to find all directories matching "{env_id}__*" pattern.
         For example, for env_id="MiniGrid-Empty-8x8-v0", it finds:
           - MiniGrid-Empty-8x8-v0__dqn_baseline__1__1718300000
           - MiniGrid-Empty-8x8-v0__dqn_baseline__1__1718310000  (newer)
           - MiniGrid-Empty-8x8-v0__random_agent__1__1718300500

      2. Directories are sorted alphabetically. Since the timestamp is the last
         component, chronologically newer runs come later in the sorted order.

      3. For each run, it reads config.json (to get exp_name like "dqn_baseline")
         and episodes.csv (to get the actual training data).

      4. It stores runs in a dictionary keyed by exp_name. When multiple runs
         have the same exp_name, the later one (newer timestamp) overwrites
         the earlier one, ensuring we only keep the latest.

    Parameters
    ----------
    results_dir : str
        Path to the directory containing run folders (default: "results").
    env_id : str
        The gymnasium environment ID to filter runs for.

    Returns
    -------
    list[tuple]
        A list of (run_dir_name, config_dict, rows_list) tuples, one per experiment type.
        Each row in rows_list is a dict with keys: global_step, episodic_return,
        goal_reached, epsilon.
    """
    runs_by_exp = {}

    # sorted() ensures directories are processed in chronological order (by timestamp)
    for run_dir in sorted(Path(results_dir).glob(f"{env_id}__*")):
        config_path = run_dir / "config.json"
        episode_path = run_dir / "episodes.csv"

        # Skip incomplete runs (missing config or episode data)
        if not config_path.exists() or not episode_path.exists():
            continue

        # Read the experiment configuration
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)

        # Read all episode-level metrics from the CSV file
        rows = []
        with open(episode_path, "r", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                rows.append(
                    {
                        "global_step": int(row["global_step"]),
                        "episodic_return": float(row["episodic_return"]),
                        "goal_reached": float(row["goal_reached"]),
                        "epsilon": float(row["epsilon"]),
                    }
                )

        # Also load metrics.csv which contains the per-step td_loss and q_values
        metric_path = run_dir / "metrics.csv"
        metric_rows = []
        if metric_path.exists():
            with open(metric_path, "r", encoding="utf-8") as f:
                for row in csv.DictReader(f):
                    loss_val = row.get("td_loss", "nan")
                    try:
                        loss_val = float(loss_val)
                    except ValueError:
                        loss_val = float("nan")
                    metric_rows.append(
                        {
                            "global_step": int(row["global_step"]),
                            "td_loss": loss_val,
                        }
                    )

        if rows:
            exp_name = config["exp_name"]
            seed = int(config["seed"])
            
            if exp_name not in runs_by_exp:
                runs_by_exp[exp_name] = {}
            
            # Keying by seed means that if we encounter a newer directory for the same
            # seed (because Path.glob is sorted alphabetically by timestamp), it will
            # safely overwrite the old one!
            runs_by_exp[exp_name][seed] = (run_dir.name, config, rows, metric_rows)

    # Convert the inner dicts back to lists for the rest of the script
    for exp_name in runs_by_exp:
        runs_by_exp[exp_name] = list(runs_by_exp[exp_name].values())

    return runs_by_exp  # dict: exp_name -> list of (run_dir_name, config, rows, metric_rows)


# ============================================================================
# FIGURE HELPER
# ============================================================================

AGENT_COLORS = {
    "random_agent":       "dimgray",
    "dqn_baseline":       "steelblue",
    "dqn_reward_shaping": "darkorange",
}
LINE_STYLES = ["-", "--", ":", "-."]


def plot_figure(runs_by_exp, env_id, output_path, rolling_window, title_suffix=""):
    """
    Creates and saves a 3-panel comparison figure from a (possibly filtered)
    runs_by_exp dictionary.

    Parameters
    ----------
    runs_by_exp : dict
        {exp_name: [(run_dir_name, config, rows, metric_rows), ...]}
        May contain one seed or multiple seeds per agent.
    env_id : str
        Used for the panel titles.
    output_path : Path
        Where to save the PNG.
    rolling_window : int
        Smoothing window size.
    title_suffix : str
        Appended to every panel title (e.g. " | Seed 2").
    """
    fig, axes = plt.subplots(3, 1, figsize=(10, 11), sharex=True)

    any_dqn_config = None

    for exp_name, run_list in runs_by_exp.items():
        base_color = AGENT_COLORS.get(exp_name, "black")

        for i, (_, config, rows, metric_rows) in enumerate(run_list):
            seed = config["seed"]
            ls   = LINE_STYLES[i % len(LINE_STYLES)]

            if i == 0:
                label = f"{exp_name}  s={seed}"
            else:
                label = f"s={seed}"

            steps   = [r["global_step"] for r in rows]
            returns = rolling([r["episodic_return"] for r in rows], rolling_window)
            goals   = rolling([r["goal_reached"]   for r in rows], rolling_window)

            axes[0].plot(steps, returns, label=label, color=base_color, linestyle=ls, linewidth=1.5)
            axes[1].plot(steps, goals,   label=label, color=base_color, linestyle=ls, linewidth=1.5)

            if metric_rows:
                ls_steps = [r["global_step"] for r in metric_rows]
                lv       = rolling([r["td_loss"] for r in metric_rows], rolling_window)
                valid    = [(s, l) for s, l in zip(ls_steps, lv) if l == l]
                if valid:
                    vs, vl = zip(*valid)
                    axes[2].plot(vs, vl, label=label, color=base_color, linestyle=ls, linewidth=1.5)

            if exp_name != "random_agent":
                any_dqn_config = config

    axes[0].set_title(f"{env_id} — Episodic Return{title_suffix}")
    axes[0].set_ylabel("Return")
    axes[0].grid(alpha=0.3)
    axes[0].legend(fontsize=8)

    axes[1].set_title(f"{env_id} — Goal Reached Rate{title_suffix}")
    axes[1].set_ylabel("Goal Rate")
    axes[1].set_ylim(-0.05, 1.05)
    axes[1].grid(alpha=0.3)
    axes[1].legend(fontsize=8)

    axes[2].set_title(f"{env_id} — TD Loss{title_suffix}")
    axes[2].set_ylabel("TD Loss")
    axes[2].set_xlabel("Training Steps")
    axes[2].grid(alpha=0.3)
    axes[2].legend(fontsize=8)

    # Secondary X-axis: Epsilon
    ax_eps = axes[2].twiny()
    ax_eps.set_xlim(axes[2].get_xlim())
    ax_eps.xaxis.set_ticks_position("bottom")
    ax_eps.xaxis.set_label_position("bottom")
    ax_eps.spines["bottom"].set_position(("outward", 40))
    ax_eps.set_xlabel("Exploration Rate (Epsilon)")

    ticks = axes[2].get_xticks()
    ax_eps.set_xticks(ticks)

    if any_dqn_config:
        start_e = any_dqn_config.get("start_e", 1.0)
        end_e   = any_dqn_config.get("end_e", 0.0)
        frac    = any_dqn_config.get("exploration_fraction", 0.6)
        total   = any_dqn_config.get("total_timesteps", 50000)
        slope   = (end_e - start_e) / (frac * total)
        eps_labels = []
        for t in ticks:
            if t < 0 or t > total:
                eps_labels.append("")
            else:
                eps_labels.append(f"{max(slope * t + start_e, end_e):.2f}")
        ax_eps.set_xticklabels(eps_labels)

    fig.tight_layout()
    fig.savefig(output_path, dpi=160)
    plt.close(fig)
    print(f"Saved {output_path}")


# ============================================================================
# MAIN PLOTTING FUNCTION
# ============================================================================

def main():
    """
    Entry point: parses arguments, loads all runs, then generates:
      1. One comparison plot per seed  ->  {env_id}_comparison_seed{N}.png
      2. One combined plot (all seeds) ->  {env_id}_comparison_all.png
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--env-id",        type=str, required=True)
    parser.add_argument("--results-dir",   type=str, default="results")
    parser.add_argument("--plots-dir",     type=str, default="plots")
    parser.add_argument("--rolling-window",type=int, default=20)
    args = parser.parse_args()

    runs_by_exp = load_runs(args.results_dir, args.env_id)
    if not runs_by_exp:
        raise SystemExit(f"No runs found for {args.env_id} in {args.results_dir}")

    Path(args.plots_dir).mkdir(parents=True, exist_ok=True)
    plots_dir = Path(args.plots_dir)

    # --- Discover all DQN seeds present ---
    all_seeds = set()
    for exp_name, run_list in runs_by_exp.items():
        if exp_name == "random_agent":
            continue
        for _, config, _, _ in run_list:
            all_seeds.add(int(config["seed"]))
    all_seeds = sorted(all_seeds)

    print(f"Found DQN seeds: {all_seeds} for {args.env_id}")

    # --- Generate One comparison plot per seed ---
    for seed in all_seeds:
        # Filter each agent's run list to only this seed
        # Random agent only ran once (seed 1), so we include it in ALL plots
        filtered = {}
        for exp_name, run_list in runs_by_exp.items():
            if exp_name == "random_agent":
                filtered[exp_name] = run_list
            else:
                seed_runs = [(d, c, r, m) for d, c, r, m in run_list if int(c["seed"]) == seed]
                if seed_runs:
                    filtered[exp_name] = seed_runs

        if not filtered:
            continue

        out = plots_dir / f"{args.env_id}_comparison_seed{seed}.png"
        plot_figure(filtered, args.env_id, out, args.rolling_window,
                    title_suffix=f" | Seed {seed}")


if __name__ == "__main__":
    main()
